#!/usr/bin/python3

import argparse
import json
import pathlib
import sys

from bureaucracy import VogonPoet

parser = argparse.ArgumentParser(description="~@ vogon @~")

parser.add_argument(
    "-i",
    "--image",
    help="Name of Docker image to start the vogon container, if not using the vogon default.",
)

parser.add_argument(
    "-m",
    "--mnt-dir",
    help="Mount a local host directory to /mnt within the container.",
)

parser.add_argument(
    "-j",
    "--jupyterlab",
    help="Run a JupyterLab session out of the container, using /mnt.",
    action="store_true",
)

def main():
    args = parser.parse_args()

    vogon_homedir_config_file = pathlib.Path.home() / ".vogonconfig"

    if vogon_homedir_config_file.exists():
        with open(vogon_homedir_config_file, "r") as fh:
            vogon_config = json.load(fh)
    else:
        vogon_config = {}

    vogon_pwd_config_file = pathlib.Path(".") / ".vogonconfig"
    if vogon_pwd_config_file.exists():
        with open(vogon_pwd_config_file, "r") as fh:
            vogon_pwd_config = json.load(fh)

        vogon_config = {**vogon_config, **vogon_pwd_config}

    if args.image:
        image = args.image
    elif vogon_config.get("image", None):
        image = vogon_config["image"]
    else:
        raise Exception(
            "No image name specified. Either use the -i flag or define an image key in your ~/.vogonconfig file."
        )

    poet = VogonPoet(
        docker_image_name=image,
        repo_dir=".",
        mnt_dir=args.mnt_dir,
        start_jupyter_lab=args.jupyterlab,
        config=vogon_config
    )

    poet.launch()


if __name__ == "__main__":
    sys.exit(main())
