#!/usr/bin/env python

import argparse
import sys

from bureaucracy import VogonExplorer, VogonPoet

subcommands = ["poet", "explorer", "build"]

parser = argparse.ArgumentParser(description="~@ vogon @~")
subparsers = parser.add_subparsers()

subparser_poet = subparsers.add_parser("poet")
subparser_explorer = subparsers.add_parser("explorer")
subparser_build = subparsers.add_parser("build")

for name, subparser in {"poet": subparser_poet, "explorer": subparser_explorer}.items():

    subparser.set_defaults(variant=name)

    subparser.add_argument(
        "-i", "--image", help="Use a different docker image", default="vogon",
    )

    subparser.add_argument(
        "-r",
        "--repo",
        help="Mount a local directory as a repo (defaults to the current directory)",
        default=".",
    )

    subparser.add_argument(
        "-m", "--mnt-dir", help="Mount a local directory as a docker volume"
    )

    subparser.add_argument(
        "-j", "--jupyterlab", help="start a jupyterlab session", action="store_true",
    )

    subparser.add_argument(
        "-p",
        "--python-version",
        choices=["3.8", "3.9"],
        help="Python version to use",
        default="3.8",
    )


def main():
    args = parser.parse_args()

    repo_dir, mnt_dir, mnt_volume = None, None, None

    if args.variant == "poet":
        vogon = VogonPoet(
            docker_image_name=args.image,
            repo_dir=args.repo,
            mnt_dir=args.mnt_dir,
            start_jupyter_lab=args.jupyterlab,
            python_version=args.python_version,
        )
        vogon.run()

    elif args.variant == "explorer":
        raise NotImplementedError("hold yo' horses")

    else:
        raise Exception("whaaaa")


if __name__ == "__main__":
    sys.exit(main())
